@PatientBooking.Api_HostAddress = https://localhost:7195
@json = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJQYXRpZW50Qm9va2luZ0FwaUNsaWVudCIsImlzcyI6IlBhdGllbnRCb29raW5nQXBpIiwiZXhwIjoxNzg3OTE5NzA2LCJzdWIiOiJiMjUzYWM2YS0zYjIxLTRlMzItODNmYy1iZDZlMmQ5YmYyNmEiLCJlbWFpbCI6InVzZXI0QGVtYWlsLmNvbSIsImp0aSI6ImQ3Njk0MDZmLTJjNmItNDgzOS1iM2EzLWYxY2ExMTc4ZGQ5NCIsIm5hbWUiOiJKb2huIExhc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJQYXRpZW50IiwiaWF0IjoxNzg3OTE4ODA2LCJuYmYiOjE3ODc5MTg4MDZ9.mIJDPYfC9fqu9y9A38KCXx29du5D2RiO95LOt6WHLvM

###

POST {{PatientBooking.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "Email": "user5@email.com",
  "Password": "Password!!!123",
  "FirstName": "John",
  "LastName": "Last"
}

###

POST {{PatientBooking.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Email": "user5@email.com",
  "Password": "Password!!!123"
}

###

@userId=string
GET {{PatientBooking.Api_HostAddress}}/api/auth/confirm-email?userId={{userId}}&token={{token}}
Content-Type: application/json
{
  "Email": "user3@email.com"
}

###

POST {{PatientBooking.Api_HostAddress}}/api/auth/resend-confirmation
Content-Type: application/json

{
  "Email": "user3@email.com"
}

###
